
#input OTF_SETUP_TARGET_NAME
#input OTF_SETUP_SOURCES
#input OTF_SETUP_HEADERS
MACRO(OTF_SETUP_LIBRARY)

    SET(HEADERS_GROUP "Header Files")
    SOURCE_GROUP( ${HEADERS_GROUP} FILES ${OTF_SETUP_HEADERS})

    # OTF_SETUP_FLAGS()
    # OTF_SETUP_SELECT()

    
    SET( OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin )
if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin64) #64bit
endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")

	IF(BUILD_STATIC_LIBRAY)
		ADD_DEFINITIONS(-DOTF_LIBRARY_STATIC)
		ADD_LIBRARY(${OTF_SETUP_TARGET_NAME} STATIC ${OTF_SETUP_HEADERS} ${OTF_SETUP_SOURCES})
	ELSE(BUILD_STATIC_LIBRAY)
		# ADD_DEFINITIONS(-DOTF_LIBRARY)
		SET (LIBRARY_TAG  -D${OTF_SETUP_TARGET_NAME}_LIBRARY)
		STRING(TOUPPER ${LIBRARY_TAG} LIBRARY_TAG )
		# MESSAGE(${LIBRARY_TAG})
		ADD_DEFINITIONS(${LIBRARY_TAG})
		ADD_LIBRARY(${OTF_SETUP_TARGET_NAME} SHARED ${OTF_SETUP_HEADERS} ${OTF_SETUP_SOURCES})
	ENDIF(BUILD_STATIC_LIBRAY)
	
	SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX})

    SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES FOLDER "Core")
    
	# TARGET_LINK_LIBRARIES(${OTF_SETUP_TARGET_NAME}
		# opengl32 glu32 
		# )

ENDMACRO(OTF_SETUP_LIBRARY)

#input OTF_SETUP_TARGET_NAME
#input OTF_SETUP_SOURCES
#input OTF_SETUP_HEADERS
MACRO(OTF_SETUP_EXECUTABLE)

    SET(HEADERS_GROUP "Header Files")
    SOURCE_GROUP( ${HEADERS_GROUP} FILES ${OTF_SETUP_HEADERS})

    # OTF_SETUP_FLAGS()
    # OTF_SETUP_SELECT()
    
    SET( OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin )
if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin64) #64bit
endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    
    
	IF(BUILD_STATIC_LIBRAY)
		ADD_DEFINITIONS(-DOTF_LIBRARY_STATIC)
	ENDIF(BUILD_STATIC_LIBRAY)
    

    ADD_EXECUTABLE(${OTF_SETUP_TARGET_NAME} ${OTF_SETUP_HEADERS} ${OTF_SETUP_SOURCES})
	
	SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES PROJECT_LABEL "${OTF_SETUP_TARGET_NAME}")
	SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
	SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES OUTPUT_NAME ${OTF_SETUP_TARGET_NAME})
	# SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX})


    SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES FOLDER "App")
	# TARGET_LINK_LIBRARIES(${OTF_SETUP_TARGET_NAME}
		# opengl32 glu32 
        # ${OPENGL_LIBRARIES}
        # ${OPENGL_gl_LIBRARY}
        # /usr/lib/libGL.dll.a
		# ${WOSG_LIBRARY_ALL}
		# ${WOSG_LIBRARY_ALL_PLUGINS}
		# ${WOSG_LIBRARY_ALL_DEPEND}
		# )

ENDMACRO(OTF_SETUP_EXECUTABLE)

#input OTF_SETUP_TARGET_NAME
#input OTF_SETUP_SOURCES
#input OTF_SETUP_HEADERS
MACRO(OTF_SETUP_PLUGINS)

    SET(HEADERS_GROUP "Header Files")
    SOURCE_GROUP( ${HEADERS_GROUP} FILES ${OTF_SETUP_HEADERS})

    # OTF_SETUP_FLAGS()
    # OTF_SETUP_SELECT()
    
    SET( OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin )
if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin64) #64bit
endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    
	IF(BUILD_STATIC_LIBRAY)
		ADD_DEFINITIONS(-DOTF_LIBRARY_STATIC)
		ADD_LIBRARY(${OTF_SETUP_TARGET_NAME} STATIC ${OTF_SETUP_HEADERS} ${OTF_SETUP_SOURCES})
	ELSE(BUILD_STATIC_LIBRAY)
		ADD_DEFINITIONS(-DOTF_PULGINS_LIBRARY)
		ADD_LIBRARY(${OTF_SETUP_TARGET_NAME} SHARED ${OTF_SETUP_HEADERS} ${OTF_SETUP_SOURCES})
	ENDIF(BUILD_STATIC_LIBRAY)
	
	SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX})
    SET_TARGET_PROPERTIES(${OTF_SETUP_TARGET_NAME} PROPERTIES FOLDER "Plugins")
	TARGET_LINK_LIBRARIES(${OTF_SETUP_TARGET_NAME}
		# opengl32 glu32 
        # ${OPENGL_LIBRARIES}
		# ${WOSG_LIBRARY_ALL}
		# ${WOSG_LIBRARY_ALL_PLUGINS}
		# ${WOSG_LIBRARY_ALL_DEPEND}
		nbPlugins
		)

ENDMACRO(OTF_SETUP_PLUGINS)